### ISSUE TITLE
Catkins error

### ISSUE THREAD

**Issue by ShreyaIAB** [aliaxam153/ORB_SLAM3#1]
Hi, I followed ur tutorial and got stuck at this step after running the commands 

echo "Configuring and building ORB_SLAM3 ..."
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release 
present in the build.sh

CMake Error at CMakeLists.txt:34 (find_package):
  By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one.

  Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu20/dev/ORB_SLAM3/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu20/dev/ORB_SLAM3/build/CMakeFiles/CMakeError.log".

**Comment by aliaxam153** [comment]
It seems like CMake is unable to find the catkin package, which is required for building ORB_SLAM3. This typically happens if the ROS environment is not properly set up. Make sure that ros noetic is installed. And then ensure that the ROS environment is sourced. Add the following line at the end of your ~/.bashrc file:

```
source /opt/ros/noetic/setup.bash
```
Then, source the file:
```
source ~/.bashrc
```
You can watch the part of the video at [4:10](https://youtu.be/1JnIU3kLH0c?si=FgmZ9EGrrKGBIa4B) where this step is done. I hope this will solve your problem. Let me know if it works, then I will close the issue after confirmation.

**Comment by ShreyaIAB** [comment]
Hi, i thanks for your help. I was able to fix this issue. Please close it. I do have a new error, so i will raise a new issue

**Comment by ShreyaIAB** [comment]
Thanks for help
